/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_LOTTIE_FILES           1
#define MMAP_LOTTIE_CHECKSUM        0x8D38

enum MMAP_LOTTIE_LISTS {
    MMAP_LOTTIE_CHATBOT_JSON = 0,        /*!< chatbot.json */
};
